name = "weightly-api"
main = "worker/index.js"
compatibility_date = "2026-09-24"
compatibility_flags = ["nodejs_compat"]

[vars]
WEB_ORIGIN = "https://weightly.kinn-kinn.com"
BETTER_AUTH_URL = "https://weightly.kinn-kinn.com"

[[d1_databases]]
binding = "DB"
database_name = "weightly"
database_id = "cd9c1a48-079d-4404-a077-14f7b6124327"
migrations_dir = "migrations"
